### ISSUE TITLE
Support for history-api-fallback

### ISSUE THREAD

**Issue by cmelion** [turrisjs/generator-turris#11]
404s will fallback to /index.html

**Comment by yamalight** [comment]
So, what'd be better initially - just a fallback to "home" or a separate 404 page/route?

**Comment by cmelion** [comment]
Have the server always send /index.html on 404 (and 403?).  The SPA will detect if the route is invalid and display a 404 page/view.

index.html will set the base href as appropriate.  In DEV the base href is just "/":

```
<head>
   <base href="/">
</head>
```

This lets us refresh the page no matter what route is currently active in DEV, instead of having to navigate to "home" first.  Enabling hot-loading would make this behavior unnecessary, or at least less of an issue.

**Comment by yamalight** [comment]
That's not what I meant, sorry for being unclear. With SPA server will always serve index.html, yes.

I mean, should the SPA itself when the route's not found just redirect to home page (as in `404 -> /`) ? Or should there be an additional NotFound route/page (as in `404 -> /notfound`)?

**Comment by cmelion** [comment]
Sorry, the latter, 404 -> /notfound

**Comment by yamalight** [comment]
Okay, cool. Will do.

**Comment by yamalight** [comment]
@cmelion just fyi - v0.3.0 is out, includes this enhancement + pages and components tests + more self-contained components stuff

**Comment by cmelion** [comment]
Good stuff!  I've got your latest and will let you know if I run into any
issues.

Thanks!

**Comment by yamalight** [comment]
@cmelion great, thanks for feedback!
