### ISSUE TITLE
How to proxy ajax requests?

### ISSUE THREAD

**Issue by cmelion** [turrisjs/generator-turris#18]
In the webpack config, you can (in theory) use devServer.proxy like this:

proxy: {
    '/ajax/*': 'http://your.backend/'
}

How to achieve the same thing with turris?

**Comment by yamalight** [comment]
I'd seen your PR, not sure about merging it though. Once the [issue](https://github.com/Automattic/engine.io-client/issues/376) blocking usage of hot reloading is solved, I'll switch to using webpack dev server (since it's required for hot reload). So this functionality will be enabled automatically.

Will poke the guys about engine-io issue, if they still won't fix it in next couple of day, will merge your PR.

**Comment by cmelion** [comment]
Makes sense.

**Comment by yamalight** [comment]
@cmelion Okay, looks like fix's not coming anytime soon, so here's what I'm gonna suggest:
I'd switch from serving main code with express, to serving with webpack-dev-server (this is needed for hot-reload support later) and proxy express stuff through it by default. 
How does that sounds?

**Comment by cmelion** [comment]
That sounds like the correct forward looking path.  I'll close this pull request.
Let me know if you need me to implement the webpack-dev-server.
Also have you looked at https://github.com/darul75/web-react ?

**Comment by yamalight** [comment]
@cmelion I think I should be able to do this myself today or tomorrow, but thanks for offer :)

I haven't seen this specific repo, but it looks quite generic - there are tons of examples/starters like this. And all of them are strongly opinionated (e.g. use specific things like Alt for Flux, Immutable for data, etc). I want Turris to be a bit more flexible in this regard and give more space to play around with stuff on top of default React app structure.

**Comment by cmelion** [comment]
@yamalight agree about the flexibility, was primarily interested in the hot-loading capabilities in conjunction with jsdom testing without the io.js dependency.

**Comment by yamalight** [comment]
@cmelion ah, that's a good point. will investigate if it's possible to use something that works both in node and iojs.

btw, proxying is done and up in v0.5.0. Documented in readme of [turris-gulp-tasks](https://github.com/turrisjs/turris-gulp-tasks)

**Comment by cmelion** [comment]
@yamalight thanks!
