### ISSUE TITLE
How to override webpack.defaults.js

### ISSUE THREAD

**Issue by cmelion** [turrisjs/generator-turris#2]
Some of the npm modules I'm using only expose es6.
Adding the module as a special case in webpack.defaults.js works but there needs to be a way to override on a project-by-project basis, via webpack.config.js, for example.
Alternative approach would be to load the dependency as a bower_component.

```
    module: {
        loaders: [
            .
            .
            .
            {
                test: /cortexjs/,
                loader: 'babel'
            },
            .
            .
            .
        ],
    },
```

**Comment by cmelion** [comment]
Issue resolved by adding the following to webpack.config.js:
    module: {
        loaders: [

            {
                test: /cortexjs/,
                loader: 'babel'
            },
            {
                test: /\.jsx?$/,
                exclude: /node_modules/,
                loaders: ['react-hot', 'babel'],
            }
        ]
    }

**Comment by yamalight** [comment]
I'd just published the updated turris-gulp-tasks (and updated generators) that will properly deep-merge the arrays in config, so your snippet should now work.
Either re-scaffold your component with new generator version, of alternatively just update turris-gulp-tasks to v0.3.0 in package.json

**Comment by cmelion** [comment]
Yep, that works.  Thanks!
