### ISSUE TITLE
Allow picking from Bootstrap and Material Design Lite css frameworks

### ISSUE THREAD

**Issue by yamalight** [turrisjs/generator-turris#25]
Google has just rolled out [Material Design Lite](https://github.com/google/material-design-lite), looks pretty good, might be worth switching.

**Comment by yamalight** [comment]
@cmelion you are one of the active users - have any opinion on this? any reason to stick to old Twitter Bootstrap?

**Comment by cmelion** [comment]
I'm all for switching to Material Design as the default.  Long term it would be nice to enhance the generator to allow a choice during the initial app generation.  Same for SASS and LESS (though webpack supports having both in the same project).

**Comment by yamalight** [comment]
@cmelion Switching is a good point. The only problem I see here is that you'll have to pick every time you generate components too then (since they'll have different classes/layout).

w.r.t adding sass - it's pretty easy, just adding a new loader to turris-gulp-tasks will solve everything. will add a ticket there, and implement it later.

**Comment by cmelion** [comment]
For me, switching layout engines is a pretty low priority.  That said, generated components should be pretty light-weight in terms of css, just an empty less/sass file with a component wrapper class.  Would Material Design really change that paradigm?

**Comment by yamalight** [comment]
@cmelion well, size-wise both Bootstrap and Material-Design-Lite are more or less the same (difference is within 1kb). But writing HTML is quite much simpler for MDL since it doesn't have millions of nested divs that are common for Bootstrap.
Also, I just like material design in general :D

**Comment by cmelion** [comment]
@yamalight MDL sure looks nicer in terms of markup so I'm all for using it.  My response was more in terms of how it would change component generation, I didn't think it would have much impact.

**Comment by yamalight** [comment]
@cmelion oh, not much at all, just the template.jsx essentially

**Comment by yamalight** [comment]
Looks like allow switching during generation will be a better option here.
Still blocked because of the module issue: https://github.com/google/material-design-lite/issues/833
