### ISSUE TITLE
Put CSS files next to pages/components instead of putting all CSS files under `styles/` folder

### ISSUE THREAD

**Issue by pavelnikolov** [turrisjs/generator-turris#28]
Each page/component folder would contain all styles, scripts, templates (and ideally the related test files).

**Comment by yamalight** [comment]
Not sure what you mean here - each component does have separate style files included.
And in page you generally don't want to have any specific css.

**Comment by pavelnikolov** [comment]
I meant that every component or page folder should also contain a CSS file counting the styles related to that page/component, instead of having all CSS files in the common `styles` folder.

**Comment by yamalight** [comment]
@pavelnikolov components already have separate style files included

**Comment by yamalight** [comment]
@pavelnikolov just to elaborate my point here: components already have separate styles and I don't see any good case for pages having them. typically page render methods would look like this:

``` js
const render = function() {
    return (
        <Chrome>
            <Navigation />
            <PostView />
            <UserInfo />
        </Chrome>
    );
};
```

So, I don't really see any point in adding page-specific styles here. But are free to try to persuade me otherwise about this :)

**Comment by cmelion** [comment]
I haven't seen a huge need to have page specific styling, but when it does happen I just add the sass/less file and it's import statement manually.

Global styles will be application wide and the page should be primarily built via components which would have their own styles.

**Comment by yamalight** [comment]
@cmelion yup, that's pretty much same approach I typically use.
Guess I'm just gonna close this one.
