### ISSUE TITLE
Page tests fail.

### ISSUE THREAD

**Issue by cmelion** [turrisjs/generator-turris#30]
The generated tests for pages fail.

turris-page-test cfulneck$ gulp test
[10:29:23] Using gulpfile /software/scratch/turris-page-test/gulpfile.js
[10:29:23] Starting 'test'...
/software/scratch/turris-page-test/src/pages/test/index.js:32
exports.Page = Page;
               ^
ReferenceError: Page is not defined

---

Removing "export {Page};" results in:

  Test page suite
Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components).
Warning: Only functions or strings can be mounted as React components.
    1) Should render

  1 passing (323ms)
  1 failing

  1) Test page suite Should render:
     TypeError: Cannot read property 'toUpperCase' of undefined
      at Context.<anonymous> (test/page-test.jsx:18:32)

[10:38:33] 'test' errored after 2.25 s
[10:38:33] Error in plugin 'gulp-spawn-mocha'

**Comment by yamalight** [comment]
oh, right. I'm an idiot, completely forgot about that. will fix asap!

**Comment by yamalight** [comment]
@cmelion done and published. thanks for reporting!

**Comment by cmelion** [comment]
@yamalight you are fast :-)

**Comment by yamalight** [comment]
@cmelion when issues are that silly - yes :smile:
