### ISSUE TITLE
Change from turris-gulp-tasks to plain dependencies

### ISSUE THREAD

**Issue by yamalight** [turrisjs/generator-turris#32]
Switching from mocha to tap will mean that it's possible to run all needed things using npm scripts, if we do this, maybe there's no need for gulp and turris-gulp-tasks at all? 
Need to investigate that.

**Comment by cmelion** [comment]
turris-gulp-tasks have lead to some difficulties for us.  We have been able to work-around all of them but I'm all for removing the dependency on gulp and relying on npm scripts.

**Comment by yamalight** [comment]
@cmelion what were the issues (i'm really curious)?
but, yeah, the more I think about it, the more it looks like separate gulp tasks repo is redundant

**Comment by cmelion** [comment]
First issue was developer confusion over where the tasks lived.
Second issue was the dependency on IO.js or more precisely latest version of jsdom.

We ended up overriding test, cover and deploy in our local gulp folder, i.e.

var mocha = require('gulp-spawn-mocha');
var config = require('../buildConfig');

module.exports = function(gulp) {
    gulp.task('test', function() {
        console.log('Libby-Client/gulp/test.js');
        gulp
            .src(config.testEntryPoint)
            .pipe(mocha({
                compilers: 'jsx?:babel/register'
            }));
    });
};

**Comment by yamalight** [comment]
done. released in 0.8.0.
