### ISSUE TITLE
Using hyphenation instead of camelCase for filenames and css classes

### ISSUE THREAD

**Issue by cmelion** [turrisjs/generator-turris#33]
Instead of:
/component-dateTimeSelector.jsx

Opt for:
/component-date-time-selector.jsx

I know there is no universally accepted approach, however ... https://github.com/turrisjs/generator-turris/issues/new

*notice the lack of upper case in the url

**Comment by yamalight** [comment]
@cmelion any reason behind that aside from obvious taste matters? :)

**Comment by cmelion** [comment]
CSS:  The trend is your friend; SASS, Bootstrap, AngularJS, really most major CSS frameworks opt for hyphenation.
CSS selectors which are part of the official CSS specifications use dashes (such as pseudo-classes like :first-child and pseudo-elements :first-line), not underscores. Same thing for properties, e.g. text-decoration, background-color, etc. Programmers are creatures of habit. It makes sense that they would follow the standard's style if there's no good reason not to.

Filenames:  The preference for all lower-case is mostly not needing to hit the shift key and to avoid typos, which can result in unexpected behavior when moving between case-sensitive and non-case-sensitive OS file systems.

**Comment by yamalight** [comment]
@cmelion sounds reasonable. will do for the next release (probably around this weekend)

**Comment by cmelion** [comment]
@yamalight thanks!

**Comment by yamalight** [comment]
@cmelion that wasn't exactly a hard task :smile:
