### ISSUE TITLE
Consider support for hot-loading

### ISSUE THREAD

**Issue by cmelion** [turrisjs/generator-turris#4]
https://github.com/gaearon/react-hot-loader

**Comment by yamalight** [comment]
yeah, I'd seen it and even poked around a bit (quite some time ago). 
For some reason it didn't quite worked as expected with the current  app structure.
But I'll check again once I have some free time. Also feel free to submit a PR with it :)

**Comment by cmelion** [comment]
Working on it, new to both react and WebPack so it's not obvious yet,

**Comment by yamalight** [comment]
Webpack-dev-server currently fails to instantiate websockets because of this issue: https://github.com/Automattic/engine.io-client/issues/376
Blocked until socket.io guys close it (update seems to be ready, just not published yet)

**Comment by yamalight** [comment]
Okay, engine-io issue is resolved, now to wait while webpack-dev-server guys update their deps: https://github.com/webpack/webpack-dev-server/pull/199

**Comment by cmelion** [comment]
@yamalight is this working yet?

**Comment by yamalight** [comment]
@cmelion was on vacation, haven't re-checked yet. will probably poke around during the weekend. 
but the issue in webpack-dev-server is still open :\

**Comment by cmelion** [comment]
@yamalight thanks, hope your well rested and had a good vaca.

**Comment by yamalight** [comment]
@cmelion wasn't bad :)
just tried adding hot reload again - still some errors, but less and they are different now :smile: 
will try to dig into it a bit more during the week.

**Comment by yamalight** [comment]
@cmelion finally managed to get it working. the biggest issue was with `require('bootstrap')` and the way webpack requires whole packages when aliases are given.
there are also some small changes needed to be done to pages structure (route needs to be separated from the component). but now it works!
will probably roll out new version with hot reload this week.

**Comment by cmelion** [comment]
Great!  I ran into the Bootstrap issue with the React-Hot-Loader demo as well, but scoping the require to CSS and Fonts only solved it, as you found.  The other modification I had to make to support Jenkins build was to use an older version of jsdom  compatible with models to support our Jenkins environment.

**Comment by cmelion** [comment]
NodeJS not models, auto-correct strikes again.

**Comment by yamalight** [comment]
shipped in v0.9.0
