### ISSUE TITLE
Make components more self-contained

### ISSUE THREAD

**Issue by cmelion** [turrisjs/generator-turris#7]
By generating a style.less file in addition to the .js and .jsx files.

src/components/chrome/style.less:

```
.chrome-component {

}
```

And updating the main.less with the necessary import.
src/styles/main.less:

```
@import "../node_modules/react-grid-layout/css/styles.css";
@import "../src/app/style";
@import "../src/pages/index/style";
@import "../src/components/chrome/style";
@import "../src/components/navigation/style";
```

![image](https://cloud.githubusercontent.com/assets/752719/8144623/0b1790cc-11b5-11e5-88aa-79bb1e3843ca.png)

Pull Request is on the way.

**Comment by yamalight** [comment]
Why not use [turris component generator](https://github.com/turrisjs/generator-turris-component) if you want to have self contained component?

**Comment by cmelion** [comment]
Self contained within the project with the potential to convert to a true standalone component.  Keeping all the assets, styles and scripts co-located improves modularity, everything about the component is self-contained.  So why not just make the component standalone in the first place?  There is cost to spinning up a repo (for non-open source projects) so unless the component proves useful outside the current project it is more cost effective to keep it local.

**Comment by yamalight** [comment]
Okay, fair enough. Will add that :)
